fun v() {
    SendPayGasSeparately;
    // <- constant.builtin

    SendPayFwdFeesSeparately;
    // <- constant.builtin

    SendIgnoreErrors;
    // <- constant.builtin

    SendDestroyIfZero;
    // <- constant.builtin

    SendRemainingValue;
    // <- constant.builtin

    SendRemainingBalance;
    // <- constant.builtin

    SendOnlyEstimateFee;
    // <- constant.builtin

    ReserveExact;
    // <- constant.builtin

    ReserveAllExcept;
    // <- constant.builtin

    ReserveAtMost;
    // <- constant.builtin

    ReserveAddOriginalBalance;
    // <- constant.builtin

    ReserveInvertSign;
    // <- constant.builtin

    ReserveBounceIfActionFail;
    // <- constant.builtin

    TactExitCodeNullReferenceException;
    // <- constant.builtin

    TactExitCodeInvalidSerializationPrefix;
    // <- constant.builtin

    TactExitCodeInvalidIncomingMessage;
    // <- constant.builtin

    TactExitCodeConstraintsError;
    // <- constant.builtin

    TactExitCodeAccessDenied;
    // <- constant.builtin

    TactExitCodeContractStopped;
    // <- constant.builtin

    TactExitCodeInvalidArgument;
    // <- constant.builtin

    TactExitCodeContractCodeNotFound;
    // <- constant.builtin

    TactExitCodeInvalidStandardAddress;
    // <- constant.builtin

    TactExitCodeNotBasechainAddress;
    // <- constant.builtin
}
