fun v() {
    SendPayGasSeparately;
    // <- constant.builtin

    SendIgnoreErrors;
    // <- constant.builtin

    SendDestroyIfZero;
    // <- constant.builtin

    SendRemainingValue;
    // <- constant.builtin

    SendRemainingBalance;
    // <- constant.builtin

    SendOnlyEstimateFee;
    // <- constant.builtin

    ReserveExact;
    // <- constant.builtin

    ReserveAllExcept;
    // <- constant.builtin

    ReserveAtMost;
    // <- constant.builtin

    ReserveAddOriginalBalance;
    // <- constant.builtin

    ReserveInvertSign;
    // <- constant.builtin

    ReserveBounceIfActionFail;
    // <- constant.builtin

    Context{};
    // <- type.builtin

    SendParameters{};
    // <- type.builtin

    StateInit{};
    // <- type.builtin

    StdAddress{};
    // <- type.builtin

    VarAddress{};
    // <- type.builtin
}
